services:
  postgres:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_DB: ai-chat-bot
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 4166
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  ai-chat-service:
    build: ./chat-bot-api
    container_name: chat-bot-api
    ports:
      - "8000:8000"
    env_file:
      - ./chat-bot-api/.env
    volumes:
      - ./chat-bot-api:/app
    depends_on:
      - postgres
    restart: always
    develop:
      watch:
        - action: rebuild
          path: ./chat-bot-api
          ignore:
            - __pycache__/
            - "*.pyc"
            - .env

  frontend:
    build: ./chat-bot-frontend
    container_name: chat-bot-frontend
    ports:
      - "3000:80"
    depends_on:
      - ai-chat-service
    restart: always
    develop:
      watch:
        - action: rebuild
          path: ./chat-bot-frontend
          ignore:
            - node_modules/
            - dist/
            - "*.log"

volumes:
  postgres_data:
