version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: ai-chat-bot
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 4166
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=postgres
      - DB_NAME=ai-chat-bot
      - DB_USER=postgres
      - DB_PASSWORD=4166
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
    depends_on:
      - postgres
    volumes:
      - .:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  postgres_data: